### ISSUE TITLE
Nan problem

### ISSUE THREAD

**Issue by FrazierLei** [PacktPublishing/Learning-Generative-Adversarial-Networks#1]
After training for a while, it raised nan problem

D:\Program Files\Anaconda3\lib\site-packages\matplotlib\image.py:405: UserWarning: Warning: converting a masked element to nan.
  dv = (np.float64(self.norm.vmax) -
D:\Program Files\Anaconda3\lib\site-packages\matplotlib\image.py:406: UserWarning: Warning: converting a masked element to nan.
  np.float64(self.norm.vmin))
D:\Program Files\Anaconda3\lib\site-packages\matplotlib\image.py:412: UserWarning: Warning: converting a masked element to nan.
  a_min = np.float64(newmin)
D:\Program Files\Anaconda3\lib\site-packages\matplotlib\image.py:417: UserWarning: Warning: converting a masked element to nan.
  a_max = np.float64(newmax)
D:\Program Files\Anaconda3\lib\site-packages\matplotlib\colors.py:916: UserWarning: Warning: converting a masked element to nan.
  dtype = np.min_scalar_type(value)
D:\Program Files\Anaconda3\lib\site-packages\numpy\ma\core.py:716: UserWarning: Warning: converting a masked element to nan.
  data = np.array(a, copy=False, subok=subok)

**Comment by daigangfan** [comment]
While I met this problem too and I found after changing "AdamOptimizer" to "GradientDescentOptimizer" this will disappear. Maybe changing some parameters in Adam also can fix it.
